version: '3.8'

services:
  spark-master:
    #image: bitnami/spark:latest # build an image that referring to dockerfile instead
    build: .
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - "8080:8080"  # Spark Master Web UI
      - "7077:7077"  # Spark Master port
      - "4040:4040"  # Spark Application UI monitoring purpose
    volumes:
      - ./data:/bitnami/spark/data
      - ./SparkScripts:/opt/bitnami/spark/scripts #bind Apps to cointainer
      - ./logs:/opt/bitnami/spark/logs #mount spark logs
      - ./mnt/apps:/mnt/apps
    networks:
      - spark-network
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4g

  spark-worker:
    #image: bitnami/spark:latest # build an image that referring to dockerfile instead
    build: .
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    depends_on:
      - spark-master
    ports:
      - "8081:8081"  # Spark Worker Web UI
    volumes:
      - ./data:/bitnami/spark/data
    networks:
      - spark-network
      
  jupyterlab:
    build: .  # Build an image referring to Dockerfile
    command: python -m jupyterlab --ip "0.0.0.0" --no-browser --NotebookApp.token=''
    container_name: jupyterlab
    environment:
      - JUPYTER_ENABLE_LAB=yes  # Enable JupyterLab
      - PYSPARK_PYTHON=/opt/bitnami/python/bin/python  # Use the same Python as Spark
    ports:
      - "8888:8888"  # JupyterLab Web UI
    volumes:
      - ./app:/app  # Mount workspaces directory
    working_dir: /app
    networks:
      - spark-network
    depends_on:
      - spark-master
      
networks:
  spark-network:
    driver: bridge