version: '3.8'

services:
  spark-master:
    build: . # build an image that referring to dockerfile instead
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - "8080:8080"  # Spark Master Web UI
      - "7077:7077"  # Spark Master port
      - "4040:4040"  # Spark Application UI monitoring purpose
    volumes:
      - ./data:/bitnami/spark/data
      - ./App:/opt/bitnami/spark/scripts #bind Apps to cointainer
    networks:
      - spark-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2g

  spark-worker:
    build: . # build an image that referring to dockerfile instead
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    depends_on:
      - spark-master
    ports:
      - "8081:8081"  # Spark Worker Web UI
    volumes:
      - ./data:/bitnami/spark/data
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge